version: '{build}'
platform:
  - x64
environment:
  matrix:
    - ruby_version: "22-x64"
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem install bundler --no-document
  - bundler env
  - bundle install --retry=3
build: off
test_script:
  - bundle exec rake
